<div class="snappoints-widget">
    <div class="snappoints-widget--disclaimer">
        <span><?= __('Your custom message here how it works') ?></span>
        <a href="javascript:void(0)"><?= __('how it works') ?></a>
    </div>
    <div class="snappoints-widget--container">
        <div class="snappoints-widget--container--description">
            <div class="snappoints-widget--container--description--logo snappoints-widget--container--description--logo__small">
                <img src="https://stories-editor.hilton.com/wp-content/uploads/2022/04/honors_white_HR-1.png">
            </div>
            <div class="snappoints-widget--container--description--points">
                2,246 points
            </div>
            <div class="snappoints-widget--container--description--action">
                <a class="snappoints-widget--container--description--action--change" href="javascript:void(0)" ><?= __('Change') ?></a>
            </div>

        </div>
    </div>
</div>

