<?php
/** @var \Magento\Catalog\Block\Product\View $block
 * @var \SnapPoints\Loyalty\Helper\Config $configHelper
 */
$configHelper = $this->helper(\SnapPoints\Loyalty\Helper\Config::class);

$product = $block->getProduct();
?>
<?php if($configHelper->isPdpWidgetEnabled()): ?>
<div class="snappoints-widget" data-product-id="<?= $product->getId() ?>" data-price="<?= $product->getFinalPrice() ?>" data-mage-init='{"SnapPoints_Loyalty/js/widgets/product":{
"pointsSelector": ".snappoints-widget--container--description--points",
"logoSelector": ".snappoints-widget--container--description--logo img"
}}'>
    <div class="snappoints-widget--disclaimer">
        <span class="snappoints-widget--disclaimer--text"><?= __('Loading...') ?></span>
        <a href="javascript:void(0)" data-trigger="how-it-work-snappoints"><?= __('how it works') ?></a>
    </div>
    <div class="snappoints-widget--container">
        <div class="snappoints-widget--container--description">
            <div class="snappoints-widget--container--description--logo snappoints-widget--container--description--logo__small">
                <img src="<?= $block->getViewFileUrl('SnapPoints_Loyalty::images/loader.svg') ?>">
            </div>
            <div class="snappoints-widget--container--description--points">
                <img src="<?= $block->getViewFileUrl('SnapPoints_Loyalty::images/loader.svg') ?>">
            </div>
            <div class="snappoints-widget--container--description--action">
                <a class="snappoints-widget--container--description--action--change" href="javascript:void(0)" data-trigger="change-snappoints"><?= __('Change') ?></a>
            </div>

        </div>
    </div>
</div>
<?php endif; ?>
