<?php
/**
 * @var \TheITNerd\SocialLogin\Helper\Config $helper
 * @var \Magento\Framework\View\Element\Template $block
 */
$helper = $this->helper(\TheITNerd\SocialLogin\Helper\Config::class);
?>

<?php if($helper->isGoogleEnabled()): ?>
    <script src="https://accounts.google.com/gsi/client" async defer></script>
    <div id="g_id_onload"
         data-client_id="<?= $helper->getGoogleClientId() ?>"
         data-context="signin"
         data-ux_mode="popup"
         data-login_uri="<?= $block->getUrl('social-login/auth/callback/type/google') ?>"
         data-auto_prompt="false">
    </div>
<?php endif; ?>

<?php if($helper->isFacebookEnabled()): ?>

    <script>
        window.fbAsyncInit = function() {
            FB.init({
                appId      : '<?= $helper->getFacebookAppId() ?>',
                cookie     : true,
                xfbml      : true,
                version    : 'v2.10'
            });
            FB.AppEvents.logPageView();
        };

        (function(d, s, id){
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {return;}
            js = d.createElement(s); js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

        let checkLoginState = function(response){
            FB.getLoginStatus(function(response) {
                if(
                    response.hasOwnProperty('status')
                    && response.status === 'connected'
                ) {
                    document.getElementById('facebook_login_accessToken').value = response.authResponse.accessToken;
                    document.getElementById('facebook_login_callback').submit();
                }
            });
        }
    </script>
    <form id="facebook_login_callback" action="<?= $helper->getFacebookLoginCallback() ?>" method="post">
        <input type="hidden" id="facebook_login_accessToken" name="accessToken" value="" />
    </form>
<?php endif; ?>
