<?php
/**
 * @var \TheITNerd\SocialLogin\Helper\Config $helper
 */
$helper = $this->helper(\TheITNerd\SocialLogin\Helper\Config::class);
?>
<?php if($helper->isGoogleEnabled()): ?>
<script src="https://accounts.google.com/gsi/client" async defer></script>


<div id="g_id_onload"
     data-client_id="<?= $helper->getGoogleClientId() ?>"
     data-context="signin"
     data-ux_mode="popup"
     data-login_uri="https://theitnerd.io/social-login/auth/callback/type/google"
     data-auto_prompt="false">
</div>

<div class="g_id_signin"
     data-type="standard"
     data-shape="rectangular"
     data-theme="outline"
     data-text="signin_with"
     data-size="large"
     data-locale="pt-BR"
     data-logo_alignment="left">
</div>
<?php endif; ?>
