({
    "optimize": 'none',
    "baseUrl": "pub/static/frontend/Magento/luma/pt_BR_base",
    "dir": "pub/static/frontend/Magento/luma/pt_BR",
    "generateSourceMaps": true,
    "preserveLicenseComments": false,
    "wrapShim": true,
    "inlineText": true,
    "normalizeDirDefines": "all",
    "modules": [
        {
            "name": "bundles/shared",
            "create": true,
            "include": [
                "jquery",
                "domReady",
                "Magento_PageCache/js/form-key-provider",
                "mage/smart-keyboard-handler",
                "underscore",
                "mage/apply/scripts",
                "mage/apply/main",
                "mage/mage",
                "domReady!",
                "Magento_Theme/js/theme",
                "text",
                "js-cookie/js.cookie",
                "text!js-translation.json",
                "Magento_Translation/js/mage-translation-dictionary",
                "knockoutjs/knockout",
                "knockoutjs/knockout-es5",
                "mage/template",
                "Magento_Ui/js/lib/knockout/extender/observable_array",
                "text!ui/template/modal/modal-popup.html",
                "mage/utils/wrapper",
                "Magento_ReCaptchaWebapiUi/js/jquery-mixin",
                "mage/common",
                "js-cookie/cookie-wrapper",
                "jquery/jquery.cookie",
                "Magento_Ui/js/lib/registry/registry",
                "jquery/ui-modules/version",
                "jquery/ui-modules/widget",
                "mage/cookies",
                "Smile_ElasticsuiteTracker/js/user-consent",
                "mage/translate",
                "text!ui/template/modal/modal-slide.html",
                "text!ui/template/modal/modal-custom.html",
                "Magento_Ui/js/lib/key-codes",
                "jquery/z-index",
                "knockoutjs/knockout-repeat",
                "knockoutjs/knockout-fast-foreach",
                "Magento_Ui/js/lib/core/events",
                "Magento_Ui/js/lib/knockout/extender/bound-nodes",
                "mage/utils/strings",
                "mage/utils/arrays",
                "mage/utils/objects",
                "mage/utils/compare",
                "mage/utils/misc",
                "mage/utils/template",
                "mage/utils/main",
                "Magento_Ui/js/core/renderer/types",
                "Magento_Ui/js/lib/knockout/bindings/mage-init",
                "Magento_Ui/js/lib/knockout/bindings/optgroup",
                "Magento_Ui/js/lib/knockout/bindings/datepicker",
                "Magento_Ui/js/lib/knockout/bindings/fadeVisible",
                "Magento_Ui/js/lib/core/storage/local",
                "Magento_Ui/js/lib/logger/message-pool",
                "Magento_Ui/js/lib/logger/logger-utils",
                "Magento_Ui/js/lib/logger/levels-pool",
                "Magento_Ui/js/lib/logger/logger",
                "Magento_Ui/js/lib/logger/console-output-handler",
                "jquery/ui-modules/data",
                "jquery/ui-modules/disable-selection",
                "jquery/ui-modules/focusable",
                "jquery/ui-modules/keycode",
                "jquery/ui-modules/ie",
                "jquery/ui-modules/plugin",
                "jquery/ui-modules/jquery-patch",
                "jquery/ui-modules/scroll-parent",
                "jquery/ui-modules/tabbable",
                "jquery/ui-modules/safe-active-element",
                "Magento_Ui/js/lib/core/class",
                "Magento_Ui/js/lib/knockout/template/observable_source",
                "jquery/ui-modules/form",
                "jquery/ui-modules/safe-blur",
                "jquery/ui-modules/labels",
                "text!ui/template/tooltip/tooltip.html",
                "jquery/ui-modules/unique-id",
                "jquery/ui-modules/core",
                "Magento_Ui/js/modal/modal",
                "Magento_Ui/js/modal/confirm",
                "mage/dataPost",
                "Magento_Ui/js/lib/knockout/template/loader",
                "Magento_Ui/js/lib/knockout/template/renderer",
                "Magento_Ui/js/lib/knockout/bindings/i18n",
                "Magento_Ui/js/lib/knockout/bindings/keyboard",
                "Magento_Ui/js/lib/knockout/bindings/after-render",
                "Magento_Ui/js/lib/knockout/bindings/autoselect",
                "Magento_Ui/js/lib/knockout/bindings/outer_click",
                "Magento_Ui/js/lib/knockout/bindings/collapsible",
                "Magento_Ui/js/lib/knockout/bindings/staticChecked",
                "Magento_Ui/js/lib/knockout/bindings/simple-checked",
                "Magento_Ui/js/lib/knockout/bindings/bind-html",
                "Magento_Ui/js/lib/knockout/bindings/range",
                "Magento_Ui/js/lib/knockout/bindings/tooltip",
                "tinycolor",
                "spectrum",
                "Magento_Ui/js/lib/knockout/bindings/color-picker",
                "Magento_Ui/js/lib/logger/entry",
                "Magento_Ui/js/lib/logger/entry-factory",
                "moment",
                "Magento_Ui/js/lib/logger/formatter",
                "Magento_Ui/js/lib/logger/console-logger",
                "Magento_Ui/js/core/renderer/layout",
                "Magento_Ui/js/lib/knockout/template/engine",
                "Magento_Ui/js/lib/knockout/bindings/scope",
                "Magento_Ui/js/lib/view/utils/dom-observer",
                "Magento_Ui/js/lib/view/utils/bindings",
                "Magento_Ui/js/lib/view/utils/async",
                "Magento_Ui/js/lib/knockout/bindings/resizable",
                "Magento_Ui/js/lib/knockout/bindings/bootstrap",
                "Magento_Ui/js/lib/knockout/bootstrap",
                "mage/bootstrap",
                "Magento_Ui/js/core/app",
                "mage/loader",
                "Magento_PageCache/js/page-cache",
                "mage/trim-input",
                "Magento_PageBuilder/js/widget-initializer",
                "Magento_Theme/js/cookie-status",
                "Magento_Ui/js/block-loader",
                "Magento_Customer/js/section-config",
                "Magento_Persistent/js/view/customer-data-mixin",
                "Magento_Catalog/js/price-utils",
                "jquery/ui-modules/widgets/tabs",
                "text!ui/template/block-loader.html",
                "mage/url",
                "mage/storage",
                "TheITNerd_Brasil/js/validation-mixin",
                "Magento_Security/js/escaper",
                "Magento_ReCaptchaFrontendUi/js/registry",
                "Magento_ReCaptchaFrontendUi/js/ui-messages-mixin",
                "Magento_Ui/js/modal/alert",
                "Magento_Captcha/js/model/captchaList",
                "Magento_Ui/js/lib/core/element/links",
                "Magento_Ui/js/lib/core/element/element",
                "Magento_Ui/js/lib/core/collection",
                "jquery/ui-modules/position",
                "jquery/ui-modules/widgets/menu",
                "jquery/ui-modules/widgets/mouse",
                "jquery/ui-modules/widgets/draggable",
                "jquery/ui-modules/widgets/resizable",
                "js-storage/js.storage",
                "jquery/jquery-storageapi",
                "Magento_Customer/js/customer-data",
                "Magento_Customer/js/invalidation-processor",
                "mage/collapsible",
                "Magento_Catalog/js/product/storage/ids-storage",
                "Magento_Ui/js/lib/spinner",
                "mage/requirejs/resolver",
                "Magento_Catalog/js/product/storage/ids-storage-compare",
                "Magento_PaypalCaptcha/js/model/skipRefreshCaptcha",
                "Magento_PaypalCaptcha/js/view/checkout/defaultCaptcha-mixin",
                "jquery/ui-modules/widgets/controlgroup",
                "Magento_Ui/js/model/messages",
                "Magento_Ui/js/model/messageList",
                "Magento_Customer/js/action/login",
                "jquery/jquery.metadata",
                "jquery/validate",
                "mage/validation",
                "Magento_Customer/js/invalidation-rules/website-rule",
                "Magento_Catalog/js/product/query-builder",
                "Magento_Catalog/js/product/storage/data-storage",
                "Magento_Catalog/js/product/storage/storage-service",
                "Magento_Catalog/js/storage-manager",
                "Magento_Ui/js/form/adapter/buttons",
                "Magento_Ui/js/form/adapter",
                "Magento_Ui/js/form/form",
                "Magento_Captcha/js/action/refresh",
                "Magento_Captcha/js/model/captcha",
                "Magento_Captcha/js/view/checkout/defaultCaptcha",
                "Magento_Captcha/js/view/checkout/loginCaptcha",
                "jquery/ui-modules/jquery-var-for-color",
                "jquery/ui-modules/form-reset-mixin",
                "jquery/ui-modules/widgets/checkboxradio",
                "jquery/ui-modules/widgets/button",
                "jquery/ui-modules/widgets/dialog",
                "jquery/ui-modules/vendor/jquery-color/jquery.color",
                "jquery/ui-modules/effect",
                "jquery/ui-modules/effects/effect-blind",
                "Magento_Ui/js/view/messages",
                "jquery/ui-modules/effects/effect-fade",
                "text!ui/template/collection.html",
                "text!Magento_Ui/template/messages.html",
                "text!Magento_Captcha/template/checkout/captcha.html"
            ],
            "exclude": []
        },
        {
            "name": "bundles/catalog-category-view",
            "create": true,
            "include": [
                "Magento_Customer/js/block-submit-on-send",
                "Magento_Catalog/js/price-box",
                "jquery/jquery.parsequery",
                "matchMedia",
                "Magento_Search/js/form-mini",
                "Smile_ElasticsuiteCore/js/form-mini",
                "Magento_InventoryConfigurableProductFrontendUi/js/configurable-variation-qty",
                "Magento_InventorySwatchesFrontendUi/js/swatch-renderer",
                "mage/decorate",
                "Magento_Customer/js/model/authentication-popup",
                "Magento_Checkout/js/view/cart-item-renderer",
                "Magento_Catalog/js/view/image",
                "mage/menu",
                "Magento_Tax/js/view/checkout/minicart/subtotal/totals",
                "Magento_Msrp/js/view/checkout/minicart/subtotal/totals",
                "Magento_Catalog/js/view/compare-products",
                "Magento_Customer/js/view/customer",
                "mage/tabs",
                "Magento_Theme/js/view/messages",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/product.html",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/product-attribute.html",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/category.html",
                "text!Smile_ElasticsuiteCore/template/autocomplete/term.html",
                "Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute",
                "Magento_Catalog/js/product/view/product-ids",
                "Magento_Catalog/js/product/view/product-ids-resolver",
                "Magento_Catalog/js/product/view/product-info",
                "Magento_Catalog/js/product/view/product-info-resolver",
                "Magento_Catalog/js/catalog-add-to-cart",
                "Magento_ConfigurableProduct/js/product/view/product-info-resolver",
                "Magento_ConfigurableProduct/js/catalog-add-to-cart-mixin",
                "mage/validation/validation",
                "Magento_Swatches/js/swatch-renderer",
                "Magento_Customer/js/view/authentication-popup",
                "mage/dropdown",
                "Magento_Checkout/js/sidebar",
                "Magento_Checkout/js/view/minicart",
                "text!Magento_Checkout/template/minicart/content.html",
                "text!Magento_Customer/template/authentication-popup.html",
                "Magento_Wishlist/js/add-to-wishlist",
                "Magento_Catalog/js/product/list/toolbar",
                "Magento_Cookie/js/require-cookie",
                "Smile_ElasticsuiteCatalog/js/mouse",
                "Smile_ElasticsuiteCatalog/js/slider",
                "mage/accordion",
                "Smile_ElasticsuiteCatalog/js/jquery.ui.touch-punch.min",
                "Smile_ElasticsuiteCatalog/js/range-slider-widget",
                "Smile_ElasticsuiteCatalog/js/attribute-filter",
                "Magento_Wishlist/js/view/wishlist",
                "text!Smile_ElasticsuiteCatalog/template/attribute-filter.html",
                "text!Smile_ElasticsuiteRating/template/rating-filter.html",
            ],
            "exclude": [
                "bundles/shared"
            ]
        },
        {
            "name": "bundles/cms-index-index",
            "create": true,
            "include": [
                "Magento_Customer/js/block-submit-on-send",
                "Magento_Catalog/js/price-box",
                "jquery/jquery.parsequery",
                "matchMedia",
                "Magento_Search/js/form-mini",
                "Smile_ElasticsuiteCore/js/form-mini",
                "Magento_InventoryConfigurableProductFrontendUi/js/configurable-variation-qty",
                "Magento_InventorySwatchesFrontendUi/js/swatch-renderer",
                "mage/decorate",
                "Magento_Customer/js/model/authentication-popup",
                "Magento_Checkout/js/view/cart-item-renderer",
                "Magento_Catalog/js/view/image",
                "mage/menu",
                "Magento_Tax/js/view/checkout/minicart/subtotal/totals",
                "Magento_Msrp/js/view/checkout/minicart/subtotal/totals",
                "Magento_Catalog/js/view/compare-products",
                "Magento_Customer/js/view/customer",
                "mage/tabs",
                "Magento_Theme/js/view/messages",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/product.html",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/product-attribute.html",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/category.html",
                "text!Smile_ElasticsuiteCore/template/autocomplete/term.html",
                "Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute",
                "Magento_Catalog/js/product/view/product-ids",
                "Magento_Catalog/js/product/view/product-ids-resolver",
                "Magento_Catalog/js/product/view/product-info",
                "Magento_Catalog/js/product/view/product-info-resolver",
                "Magento_Catalog/js/catalog-add-to-cart",
                "Magento_ConfigurableProduct/js/product/view/product-info-resolver",
                "Magento_ConfigurableProduct/js/catalog-add-to-cart-mixin",
                "mage/validation/validation",
                "Magento_Swatches/js/swatch-renderer",
                "Magento_Catalog/product/view/validation",
                "Magento_Catalog/js/validate-product",
                "Magento_Customer/js/view/authentication-popup",
                "mage/dropdown",
                "Magento_Checkout/js/sidebar",
                "Magento_Checkout/js/view/minicart",
                "text!Magento_Checkout/template/minicart/content.html",
                "text!Magento_Customer/template/authentication-popup.html",
            ],
            "exclude": [
                "bundles/shared"
            ]
        },
        {
            "name": "bundles/catalog-product-view",
            "create": true,
            "include": [
                "Magento_Customer/js/block-submit-on-send",
                "Magento_Catalog/js/price-box",
                "jquery/jquery.parsequery",
                "matchMedia",
                "Magento_Search/js/form-mini",
                "Smile_ElasticsuiteCore/js/form-mini",
                "Magento_InventoryConfigurableProductFrontendUi/js/configurable-variation-qty",
                "Magento_InventorySwatchesFrontendUi/js/swatch-renderer",
                "mage/decorate",
                "Magento_Customer/js/model/authentication-popup",
                "Magento_Checkout/js/view/cart-item-renderer",
                "Magento_Catalog/js/view/image",
                "mage/menu",
                "Magento_Tax/js/view/checkout/minicart/subtotal/totals",
                "Magento_Msrp/js/view/checkout/minicart/subtotal/totals",
                "Magento_Catalog/js/view/compare-products",
                "Magento_Customer/js/view/customer",
                "mage/tabs",
                "Magento_Theme/js/view/messages",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/product.html",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/product-attribute.html",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/category.html",
                "text!Smile_ElasticsuiteCore/template/autocomplete/term.html",
                "Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute",
                "Magento_Catalog/js/product/view/product-ids",
                "Magento_Catalog/js/product/view/product-ids-resolver",
                "Magento_Catalog/js/product/view/product-info",
                "Magento_Catalog/js/product/view/product-info-resolver",
                "Magento_Catalog/js/catalog-add-to-cart",
                "Magento_ConfigurableProduct/js/product/view/product-info-resolver",
                "Magento_ConfigurableProduct/js/catalog-add-to-cart-mixin",
                "mage/validation/validation",
                "Magento_Swatches/js/swatch-renderer",
                "Magento_Catalog/product/view/validation",
                "Magento_Catalog/js/validate-product",
                "Magento_Customer/js/view/authentication-popup",
                "mage/dropdown",
                "Magento_Checkout/js/sidebar",
                "Magento_Checkout/js/view/minicart",
                "text!Magento_Checkout/template/minicart/content.html",
                "text!Magento_Customer/template/authentication-popup.html",
                "Magento_Wishlist/js/add-to-wishlist",
                "Magento_Cookie/js/require-cookie",
                "Magento_Swatches/js/catalog-add-to-cart",
                "Magento_Review/js/error-placement",
                "Magento_Review/js/submit-review",
                "Magento_Catalog/js/related-products",
                "Magento_Catalog/js/gallery",
                "text!Magento_Theme/templates/breadcrumbs.html",
                "magnifier/magnifier",
                "magnifier/magnify",
                "Magento_Theme/js/model/breadcrumb-list",
                "Magento_Theme/js/view/breadcrumbs",
                "Magento_Theme/js/view/add-home-breadcrumb",
                "Magento_Catalog/js/product/breadcrumbs",
                "text!Magento_InstantPurchase/template/confirmation.html",
                "Magento_Review/js/validate-review",
                "Magento_InstantPurchase/js/view/instant-purchase",
                "Magento_Review/js/view/review",
                "Magento_Review/js/process-reviews",
                "text!mage/gallery/gallery.html",
                "Magento_Catalog/js/product/view/provider",
                "Magento_ProductVideo/js/load-player",
                "Magento_ProductVideo/js/fotorama-add-video-events",
                "fotorama/fotorama",
                "mage/gallery/gallery",
                "text!Magento_InstantPurchase/template/instant-purchase.html",
            ],
            "exclude": [
                "bundles/shared"
            ]
        },
        {
            "name": "bundles/checkout-cart-index",
            "create": true,
            "include": [
                "Magento_Customer/js/block-submit-on-send",
                "matchMedia",
                "Magento_Search/js/form-mini",
                "Smile_ElasticsuiteCore/js/form-mini",
                "mage/decorate",
                "Magento_Customer/js/model/authentication-popup",
                "Magento_Checkout/js/view/cart-item-renderer",
                "Magento_Catalog/js/view/image",
                "mage/menu",
                "Magento_Tax/js/view/checkout/minicart/subtotal/totals",
                "Magento_Msrp/js/view/checkout/minicart/subtotal/totals",
                "Magento_Catalog/js/view/compare-products",
                "Magento_Customer/js/view/customer",
                "mage/tabs",
                "Magento_Theme/js/view/messages",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/product.html",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/product-attribute.html",
                "text!Smile_ElasticsuiteCatalog/template/autocomplete/category.html",
                "text!Smile_ElasticsuiteCore/template/autocomplete/term.html",
                "Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute",
                "Magento_Catalog/js/product/view/product-ids",
                "Magento_Catalog/js/product/view/product-ids-resolver",
                "Magento_Catalog/js/product/view/product-info",
                "Magento_Catalog/js/product/view/product-info-resolver",
                "Magento_Catalog/js/catalog-add-to-cart",
                "Magento_ConfigurableProduct/js/product/view/product-info-resolver",
                "Magento_ConfigurableProduct/js/catalog-add-to-cart-mixin",
                "mage/validation/validation",
                "Magento_Customer/js/view/authentication-popup",
                "mage/dropdown",
                "Magento_Checkout/js/sidebar",
                "Magento_Checkout/js/view/minicart",
                "text!Magento_Checkout/template/minicart/content.html",
                "text!Magento_Customer/template/authentication-popup.html",
                "mage/sticky",
                "Magento_Checkout/js/shopping-cart",
                "Magento_Checkout/js/discount-codes",
                "Magento_GiftMessage/js/model/gift-options",
                "Magento_Checkout/js/proceed-to-checkout",
                "Magento_Checkout/js/model/quote",
                "Magento_Checkout/js/model/shipping-rates-validation-rules",
                "Magento_Dhl/js/model/shipping-rates-validation-rules",
                "Magento_Dhl/js/model/shipping-rates-validator",
                "Magento_Fedex/js/model/shipping-rates-validation-rules",
                "Magento_Fedex/js/model/shipping-rates-validator",
                "Magento_Ups/js/model/shipping-rates-validation-rules",
                "Magento_Ups/js/model/shipping-rates-validator",
                "Magento_Usps/js/model/shipping-rates-validation-rules",
                "Magento_Usps/js/model/shipping-rates-validator",
                "Magento_Checkout/js/checkout-data",
                "Magento_InventoryInStorePickupFrontend/js/checkout-data-ext",
                "Smile_ElasticsuiteCore/js/validation/validator-mixin",
                "Magento_GiftMessage/js/model/gift-message",
                "Magento_OfflineShipping/js/model/shipping-rates-validation-rules/freeshipping",
                "Magento_OfflineShipping/js/model/shipping-rates-validator/freeshipping",
                "Magento_OfflineShipping/js/model/shipping-rates-validation-rules/flatrate",
                "Magento_OfflineShipping/js/model/shipping-rates-validator/flatrate",
                "Magento_OfflineShipping/js/model/shipping-rates-validation-rules/tablerate",
                "Magento_OfflineShipping/js/model/shipping-rates-validator/tablerate",
                "Magento_InventoryInStorePickupFrontend/js/model/pickup-address-converter",
                "Magento_InventoryInStorePickupFrontend/js/model/quote-ext",
                "Magento_Tax/js/view/checkout/shipping_method/price",
                "Magento_Checkout/js/action/select-shipping-method",
                "Magento_Checkout/js/model/step-navigator",
                "PayPal_Braintree/js/model/step-navigator-mixin",
                "Magento_Checkout/js/model/shipping-address/form-popup-state",
                "Magento_Checkout/js/model/totals",
                "Magento_Checkout/js/view/summary/abstract-total",
                "Magento_Tax/js/view/checkout/summary/subtotal",
                "Magento_SalesRule/js/view/summary/discount",
                "Magento_SalesRule/js/view/cart/totals/discount",
                "Magento_Checkout/js/view/summary/shipping",
                "Magento_Tax/js/view/checkout/summary/shipping",
                "Magento_Tax/js/view/checkout/cart/totals/shipping",
                "Magento_Tax/js/view/checkout/summary/grand-total",
                "Magento_Tax/js/view/checkout/cart/totals/grand-total",
                "Magento_Tax/js/view/checkout/summary/tax",
                "Magento_Tax/js/view/checkout/cart/totals/tax",
                "Magento_Weee/js/view/checkout/summary/weee",
                "Magento_Weee/js/view/cart/totals/weee",
                "Magento_Checkout/js/action/select-shipping-address",
                "Magento_Checkout/js/model/postcode-validator",
                "Magento_Checkout/js/model/url-builder",
                "Magento_GiftMessage/js/model/url-builder",
                "Magento_Checkout/js/action/select-billing-address",
                "Magento_Checkout/js/action/update-shopping-cart",
                "Magento_Checkout/js/model/error-processor",
                "Magento_GiftMessage/js/action/gift-options",
                "Magento_GiftMessage/js/view/gift-message",
                "Magento_Checkout/js/action/select-payment-method",
                "Magento_Ui/js/lib/validation/utils",
                "Magento_Ui/js/lib/validation/rules",
                "Magento_Ui/js/lib/validation/validator",
                "Magento_Ui/js/form/element/abstract",
                "Magento_Checkout/js/model/payment/method-list",
                "Magento_SalesRule/js/model/payment/discount-messages",
                "Magento_SalesRule/js/model/coupon",
                "Magento_Checkout/js/model/default-validation-rules",
                "Magento_Checkout/js/model/default-validator",
                "Magento_Checkout/js/model/default-post-code-resolver",
                "Magento_Checkout/js/model/new-customer-address",
                "Magento_Checkout/js/model/address-converter",
                "Magento_Checkout/js/model/shipping-rates-validator",
                "Magento_Dhl/js/view/shipping-rates-validation",
                "Magento_Fedex/js/view/shipping-rates-validation",
                "Magento_OfflineShipping/js/view/shipping-rates-validation/freeshipping",
                "Magento_OfflineShipping/js/view/shipping-rates-validation/flatrate",
                "Magento_OfflineShipping/js/view/shipping-rates-validation/tablerate",
                "Magento_Ups/js/view/shipping-rates-validation",
                "Magento_Usps/js/view/shipping-rates-validation",
                "Magento_InventoryInStorePickupFrontend/js/model/checkout-data-resolver-ext",
                "Magento_Checkout/js/action/create-billing-address",
                "text!Magento_GiftMessage/template/gift-message-item-level.html",
                "text!Magento_GiftMessage/template/gift-message.html",
                "Magento_Checkout/js/model/full-screen-loader",
                "Magento_Checkout/js/model/payment/place-order-hooks",
                "Magento_Customer/js/model/customer/address",
                "Magento_Customer/js/model/customer-addresses",
                "Magento_Customer/js/model/address-list",
                "Magento_Checkout/js/action/create-shipping-address",
                "Magento_Customer/js/model/customer",
                "Magento_Checkout/js/model/resource-url-manager",
                "Magento_Checkout/js/action/get-totals",
                "Magento_Checkout/js/action/set-payment-information-extended",
                "Magento_SalesRule/js/action/select-payment-method-mixin",
                "Magento_Checkout/js/model/payment-service",
                "Magento_Checkout/js/model/checkout-data-resolver",
                "Magento_Checkout/js/model/shipping-service",
                "Magento_Checkout/js/view/cart/totals",
                "Magento_Checkout/js/view/cart/shipping-rates",
                "Magento_Checkout/js/model/cart/cache",
                "Magento_Checkout/js/model/cart/totals-processor/default",
                "text!Magento_Checkout/template/cart/shipping-rates.html",
                "text!Magento_Checkout/template/cart/totals.html",
                "Magento_Checkout/js/model/shipping-rate-registry",
                "Magento_Checkout/js/model/shipping-rate-processor/new-address",
                "Magento_Checkout/js/model/cart/estimate-service",
                "Magento_Checkout/js/view/cart/shipping-estimation",
                "text!Magento_Checkout/template/minicart/subtotal.html",
                "text!Magento_Checkout/template/minicart/item/default.html",
                "text!Magento_Tax/template/checkout/summary/subtotal.html",
                "text!Magento_SalesRule/template/cart/totals/discount.html",
                "text!Magento_Tax/template/checkout/cart/totals/shipping.html",
                "text!Magento_Weee/template/checkout/summary/weee.html",
                "text!Magento_Tax/template/checkout/cart/totals/tax.html",
                "text!Magento_Tax/template/checkout/cart/totals/grand-total.html",
                "text!Magento_Checkout/template/cart/shipping-estimation.html",
                "text!Magento_Tax/template/checkout/minicart/subtotal/totals.html",
                "text!Magento_Catalog/template/product/image_with_borders.html",
                "text!Magento_Checkout/template/minicart/item/price.html",
                "text!ui/template/form/field.html",
                "text!TheITNerd_Brasil/template/ui/form/element/cepInput.html",
                "TheITNerd_Core/js/lib/postcode",
                "TheITNerd_Core/js/model/postcode",
                "jquery/ui-modules/widgets/accordion",
                "jquery/ui-modules/widgets/droppable",
                "jquery/ui-modules/effects/effect-bounce",
                "jquery/ui-modules/effects/effect-clip",
                "jquery/ui-modules/effects/effect-drop",
                "jquery/ui-modules/effects/effect-explode",
                "jquery/ui-modules/effects/effect-fold",
                "jquery/ui-modules/effects/effect-highlight",
                "jquery/ui-modules/widgets/datepicker",
                "jquery/ui-modules/effects/effect-pulsate",
                "jquery/ui-modules/effects/effect-shake",
                "jquery/ui-modules/effects/effect-slide",
                "jquery/ui-modules/effects/effect-transfer",
                "jquery/ui-modules/widgets/progressbar",
                "jquery/ui-modules/widgets/selectable",
                "jquery/ui-modules/widgets/slider",
                "jquery/ui-modules/widgets/spinner",
                "jquery/ui-modules/widgets/sortable",
                "jquery/ui-modules/widgets/tooltip",
                "jquery/timepicker",
            ],
            "exclude": [
                "bundles/shared"
            ]
        },
        {
            "name": "bundles/checkout-index-index",
            "create": true,
            "include": [
                "Magento_Checkout/js/model/quote",
                "Magento_Checkout/js/model/shipping-rates-validation-rules",
                "Magento_Checkout/js/checkout-data",
                "Magento_InventoryInStorePickupFrontend/js/checkout-data-ext",
                "Smile_ElasticsuiteCore/js/validation/validator-mixin",
                "Magento_OfflineShipping/js/model/shipping-rates-validation-rules/flatrate",
                "Magento_OfflineShipping/js/model/shipping-rates-validator/flatrate",
                "Magento_OfflineShipping/js/model/shipping-rates-validation-rules/tablerate",
                "Magento_OfflineShipping/js/model/shipping-rates-validator/tablerate",
                "Magento_InventoryInStorePickupFrontend/js/model/pickup-address-converter",
                "Magento_InventoryInStorePickupFrontend/js/model/quote-ext",
                "Magento_Tax/js/view/checkout/shipping_method/price",
                "Magento_Checkout/js/action/select-shipping-method",
                "Magento_Checkout/js/model/step-navigator",
                "PayPal_Braintree/js/model/step-navigator-mixin",
                "Magento_Checkout/js/model/shipping-address/form-popup-state",
                "Magento_Checkout/js/model/totals",
                "Magento_Checkout/js/view/summary/abstract-total",
                "Magento_Tax/js/view/checkout/summary/subtotal",
                "Magento_SalesRule/js/view/summary/discount",
                "Magento_Checkout/js/view/summary/shipping",
                "Magento_Tax/js/view/checkout/summary/shipping",
                "Magento_Tax/js/view/checkout/summary/grand-total",
                "Magento_Tax/js/view/checkout/summary/tax",
                "Magento_Weee/js/view/checkout/summary/weee",
                "Magento_Checkout/js/action/select-shipping-address",
                "Magento_Checkout/js/model/postcode-validator",
                "Magento_Checkout/js/model/url-builder",
                "Magento_Checkout/js/action/select-billing-address",
                "Magento_Checkout/js/model/error-processor",
                "Magento_Checkout/js/action/select-payment-method",
                "Magento_Ui/js/lib/validation/utils",
                "Magento_Ui/js/lib/validation/rules",
                "Magento_Ui/js/lib/validation/validator",
                "Magento_Ui/js/form/element/abstract",
                "Magento_Checkout/js/model/payment/method-list",
                "Magento_SalesRule/js/model/payment/discount-messages",
                "Magento_SalesRule/js/model/coupon",
                "Magento_Checkout/js/model/default-validation-rules",
                "Magento_Checkout/js/model/default-validator",
                "Magento_Checkout/js/model/default-post-code-resolver",
                "Magento_Checkout/js/model/new-customer-address",
                "Magento_Checkout/js/model/address-converter",
                "Magento_Checkout/js/model/shipping-rates-validator",
                "Magento_OfflineShipping/js/view/shipping-rates-validation/flatrate",
                "Magento_OfflineShipping/js/view/shipping-rates-validation/tablerate",
                "Magento_InventoryInStorePickupFrontend/js/model/checkout-data-resolver-ext",
                "Magento_Checkout/js/action/create-billing-address",
                "Magento_Checkout/js/model/full-screen-loader",
                "Magento_Checkout/js/model/payment/place-order-hooks",
                "Magento_Customer/js/model/customer/address",
                "Magento_Customer/js/model/customer-addresses",
                "Magento_Customer/js/model/address-list",
                "Magento_Checkout/js/action/create-shipping-address",
                "Magento_Customer/js/model/customer",
                "Magento_Checkout/js/model/resource-url-manager",
                "Magento_Checkout/js/action/get-totals",
                "Magento_Checkout/js/action/set-payment-information-extended",
                "Magento_SalesRule/js/action/select-payment-method-mixin",
                "Magento_Checkout/js/model/payment-service",
                "Magento_Checkout/js/model/checkout-data-resolver",
                "Magento_Checkout/js/model/shipping-service",
                "Magento_Checkout/js/model/shipping-rate-registry",
                "Magento_Checkout/js/model/shipping-rate-processor/new-address",
                "text!Magento_Tax/template/checkout/summary/subtotal.html",
                "text!Magento_Weee/template/checkout/summary/weee.html",
                "text!ui/template/form/field.html",
                "text!TheITNerd_Brasil/template/ui/form/element/cepInput.html",
                "TheITNerd_Core/js/lib/postcode",
                "TheITNerd_Core/js/model/postcode",
                "jquery/ui-modules/widgets/accordion",
                "jquery/ui-modules/widgets/droppable",
                "jquery/ui-modules/effects/effect-bounce",
                "jquery/ui-modules/effects/effect-clip",
                "jquery/ui-modules/effects/effect-drop",
                "jquery/ui-modules/effects/effect-explode",
                "jquery/ui-modules/effects/effect-fold",
                "jquery/ui-modules/effects/effect-highlight",
                "jquery/ui-modules/widgets/datepicker",
                "jquery/ui-modules/effects/effect-pulsate",
                "jquery/ui-modules/effects/effect-shake",
                "jquery/ui-modules/effects/effect-slide",
                "jquery/ui-modules/effects/effect-transfer",
                "jquery/ui-modules/widgets/progressbar",
                "jquery/ui-modules/widgets/selectable",
                "jquery/ui-modules/widgets/slider",
                "jquery/ui-modules/widgets/spinner",
                "jquery/ui-modules/widgets/sortable",
                "jquery/ui-modules/widgets/tooltip",
                "jquery/timepicker",
                "jquery/ui-modules/widgets/autocomplete",
                "TheITNerd_Core/js/lib/jquery.mask",
                "jquery/ui-modules/effects/effect-size",
                "jquery/ui-modules/effects/effect-scale",
                "jquery/compat",
                "TheITNerd_Core/js/inputMask",
                "TheITNerd_Core/js/postcode",
                "TheITNerd_Core/js/view/postcodeSearch",
                "text!TheITNerd_Core/template/postcode-search/postcodeSearch.html",
                "text!Magento_Tax/template/checkout/shipping_method/price.html",
                "Magento_Checkout/js/checkout-loader",
                "Magento_Checkout/js/model/payment/renderer-list",
                "Magento_Checkout/js/model/payment/additional-validators",
                "Magento_Checkout/js/model/payment/method-converter",
                "Magento_CheckoutAgreements/js/model/agreements-modal",
                "Magento_Shipping/js/model/config",
                "Magento_Paypal/js/view/payment/paypal-payments",
                "Magento_OfflinePayments/js/view/payment/offline-payments",
                "Magento_Payment/js/view/payment/payments",
                "Magento_Checkout/js/view/summary/item/details",
                "Magento_Checkout/js/view/summary/item/details/thumbnail",
                "Magento_Checkout/js/view/summary/item/details/message",
                "Magento_CheckoutAgreements/js/view/checkout-agreements",
                "Magento_Ui/js/form/components/group",
                "Magento_Shipping/js/view/checkout/shipping/shipping-policy",
                "Magento_Customer/js/action/check-email-availability",
                "Magento_Checkout/js/model/authentication-messages",
                "Magento_Checkout/js/view/shipping-information/list",
                "Magento_Checkout/js/view/checkout/placeOrderCaptcha",
                "Magento_PaypalCaptcha/js/view/checkout/paymentCaptcha",
                "Magento_Checkout/js/view/summary/cart-items",
                "Magento_Checkout/js/view/summary",
                "Magento_Checkout/js/view/summary/totals",
                "Magento_Weee/js/view/checkout/summary/item/price/weee",
                "Magento_Weee/js/view/checkout/summary/item/price/row_incl_tax",
                "Magento_Weee/js/view/checkout/summary/item/price/row_excl_tax",
                "Magento_Checkout/js/view/summary/item/details/subtotal",
                "Magento_Tax/js/view/checkout/summary/item/details/subtotal",
                "text!Magento_Checkout/template/onepage.html",
                "Magento_Checkout/js/action/recollect-shipping-rates",
                "Magento_CheckoutAgreements/js/model/agreement-validator",
                "Magento_CheckoutAgreements/js/view/agreement-validation",
                "Magento_PaypalCaptcha/js/view/payment/list-mixin",
                "Magento_Checkout/js/view/shipping-address/list",
                "Magento_Checkout/js/view/form/element/email",
                "Magento_Checkout/js/view/billing-address/list",
                "Magento_Checkout/js/view/authentication",
                "Magento_Checkout/js/model/customer-email-validator",
                "Magento_Checkout/js/view/payment/email-validator",
                "Magento_Checkout/js/action/get-payment-information",
                "Magento_SalesRule/js/action/set-coupon-code",
                "Magento_SalesRule/js/action/cancel-coupon",
                "Magento_SalesRule/js/view/payment/discount",
                "Magento_SalesRule/js/view/payment/captcha",
                "Magento_SalesRule/js/view/payment/discount-messages",
                "Magento_Checkout/js/view/authentication-messages",
                "Magento_Ui/js/form/element/post-code",
                "Magento_Ui/js/form/element/select",
                "Magento_Checkout/js/view/payment",
                "Magento_Checkout/js/view/payment/list",
                "Magento_Ui/js/form/element/region",
                "Magento_Checkout/js/model/sidebar",
                "Magento_Checkout/js/view/sidebar",
                "Magento_Checkout/js/action/set-billing-address",
                "Magento_Checkout/js/model/billing-address-postcode-validator",
                "Magento_Checkout/js/view/billing-address",
                "Magento_Checkout/js/model/shipping-rate-processor/customer-address",
                "Magento_Checkout/js/model/shipping-rate-service",
                "text!Magento_Checkout/template/authentication.html",
                "text!Magento_Checkout/template/sidebar.html",
                "text!Magento_Checkout/template/payment.html",
                "Magento_SalesRule/js/model/shipping-save-processor-mixin",
                "Magento_Checkout/js/model/payment/method-group",
                "Magento_Checkout/js/view/estimation",
                "text!Magento_Checkout/template/summary.html",
                "text!Magento_ReCaptchaCheckout/template/payment-recaptcha-container.html",
                "text!Magento_Checkout/template/payment-methods/list.html",
                "text!Magento_SalesRule/template/payment/discount.html",
                "Magento_Checkout/js/model/shipping-save-processor/payload-extender",
                "Magento_Checkout/js/model/shipping-save-processor/default",
                "Magento_Checkout/js/model/shipping-save-processor",
                "Magento_Checkout/js/action/set-shipping-information",
            ],
            "exclude": [
                "bundles/shared"
            ]
        }
    ],
    "shim": {
        "mage/adminhtml/backup": {
            "deps": [
                "prototype"
            ]
        },
        "mage/captcha": {
            "deps": [
                "prototype"
            ]
        },
        "mage/new-gallery": {
            "deps": [
                "jquery"
            ]
        },
        "jquery/ui": {
            "deps": [
                "jquery"
            ]
        },
        "matchMedia": {
            "exports": "mediaCheck"
        },
        "magnifier/magnifier": {
            "deps": [
                "jquery"
            ]
        },
        "vimeo/player": {
            "exports": "Player"
        },
        "Magento_Checkout/js/model/totals": {
            "deps": [
                "Magento_Customer/js/customer-data"
            ]
        },
        "chartjs/chartjs-adapter-moment": {
            "deps": [
                "moment"
            ]
        },
        "chartjs/es6-shim.min": {},
        "tiny_mce_5/tinymce.min": {
            "exports": "tinyMCE"
        },
        "cardinaljs": {
            "exports": "Cardinal"
        },
        "cardinaljsSandbox": {
            "exports": "Cardinal"
        },
        "Magento_PageBuilder/js/resource/slick/slick": {
            "deps": [
                "jquery"
            ]
        },
        "Magento_PageBuilder/js/resource/jarallax/jarallax-video": {
            "deps": [
                "jarallax-wrapper",
                "vimeoWrapper"
            ]
        },
        "vimeoAPI": {},
        "Magento_ProductVideo/js/load-player": {
            "deps": [
                "vimeoWrapper"
            ]
        },
        "Smile_ElasticsuiteCatalog/js/jquery.ui.touch-punch.min": {
            "deps": [
                "Smile_ElasticsuiteCatalog/js/mouse"
            ]
        },
        "Magento_PageBuilder/js/utils/map": {
            "deps": [
                "googleMaps"
            ]
        }
    },
    "paths": {
        "jquery/validate": "jquery/jquery.validate",
        "jquery/file-uploader": "jquery/fileUploader/jquery.fileuploader",
        "prototype": "legacy-build.min",
        "jquery/jquery-storageapi": "js-storage/storage-wrapper",
        "text": "requirejs/text",
        "domReady": "requirejs/domReady",
        "spectrum": "jquery/spectrum/spectrum",
        "tinycolor": "jquery/spectrum/tinycolor",
        "jquery-ui-modules": "jquery/ui-modules",
        "ui/template": "Magento_Ui/templates",
        "vimeo/player/player": "vimeo/player",
        "vimeo/player/vimeo-wrapper": "vimeo/vimeo-wrapper",
    },
    "map": {
        "*": {
            "directoryRegionUpdater": "Magento_Directory/js/region-updater",
            "ko": "knockoutjs/knockout",
            "knockout": "knockoutjs/knockout",
            "mageUtils": "mage/utils/main",
            "rjsResolver": "mage/requirejs/resolver",
            "jquery-ui-modules/core": "jquery/ui-modules/core",
            "jquery-ui-modules/accordion": "jquery/ui-modules/widgets/accordion",
            "jquery-ui-modules/autocomplete": "jquery/ui-modules/widgets/autocomplete",
            "jquery-ui-modules/button": "jquery/ui-modules/widgets/button",
            "jquery-ui-modules/datepicker": "jquery/ui-modules/widgets/datepicker",
            "jquery-ui-modules/dialog": "jquery/ui-modules/widgets/dialog",
            "jquery-ui-modules/draggable": "jquery/ui-modules/widgets/draggable",
            "jquery-ui-modules/droppable": "jquery/ui-modules/widgets/droppable",
            "jquery-ui-modules/effect-blind": "jquery/ui-modules/effects/effect-blind",
            "jquery-ui-modules/effect-bounce": "jquery/ui-modules/effects/effect-bounce",
            "jquery-ui-modules/effect-clip": "jquery/ui-modules/effects/effect-clip",
            "jquery-ui-modules/effect-drop": "jquery/ui-modules/effects/effect-drop",
            "jquery-ui-modules/effect-explode": "jquery/ui-modules/effects/effect-explode",
            "jquery-ui-modules/effect-fade": "jquery/ui-modules/effects/effect-fade",
            "jquery-ui-modules/effect-fold": "jquery/ui-modules/effects/effect-fold",
            "jquery-ui-modules/effect-highlight": "jquery/ui-modules/effects/effect-highlight",
            "jquery-ui-modules/effect-scale": "jquery/ui-modules/effects/effect-scale",
            "jquery-ui-modules/effect-pulsate": "jquery/ui-modules/effects/effect-pulsate",
            "jquery-ui-modules/effect-shake": "jquery/ui-modules/effects/effect-shake",
            "jquery-ui-modules/effect-slide": "jquery/ui-modules/effects/effect-slide",
            "jquery-ui-modules/effect-transfer": "jquery/ui-modules/effects/effect-transfer",
            "jquery-ui-modules/effect": "jquery/ui-modules/effect",
            "jquery-ui-modules/menu": "jquery/ui-modules/widgets/menu",
            "jquery-ui-modules/mouse": "jquery/ui-modules/widgets/mouse",
            "jquery-ui-modules/position": "jquery/ui-modules/position",
            "jquery-ui-modules/progressbar": "jquery/ui-modules/widgets/progressbar",
            "jquery-ui-modules/resizable": "jquery/ui-modules/widgets/resizable",
            "jquery-ui-modules/selectable": "jquery/ui-modules/widgets/selectable",
            "jquery-ui-modules/selectmenu": "jquery/ui-modules/widgets/selectmenu",
            "jquery-ui-modules/slider": "jquery/ui-modules/widgets/slider",
            "jquery-ui-modules/sortable": "jquery/ui-modules/widgets/sortable",
            "jquery-ui-modules/spinner": "jquery/ui-modules/widgets/spinner",
            "jquery-ui-modules/tabs": "jquery/ui-modules/widgets/tabs",
            "jquery-ui-modules/tooltip": "jquery/ui-modules/widgets/tooltip",
            "jquery-ui-modules/widget": "jquery/ui-modules/widget",
            "jquery-ui-modules/timepicker": "jquery/timepicker",
            "vimeo": "vimeo/player",
            "vimeoWrapper": "vimeo/vimeo-wrapper",
            "rowBuilder": "Magento_Theme/js/row-builder",
            "toggleAdvanced": "mage/toggle",
            "translateInline": "mage/translate-inline",
            "sticky": "mage/sticky",
            "tabs": "mage/tabs",
            "collapsible": "mage/collapsible",
            "dropdownDialog": "mage/dropdown",
            "dropdown": "mage/dropdowns",
            "accordion": "mage/accordion",
            "loader": "mage/loader",
            "tooltip": "mage/tooltip",
            "deletableItem": "mage/deletable-item",
            "itemTable": "mage/item-table",
            "fieldsetControls": "mage/fieldset-controls",
            "fieldsetResetControl": "mage/fieldset-controls",
            "redirectUrl": "mage/redirect-url",
            "loaderAjax": "mage/loader",
            "menu": "mage/menu",
            "popupWindow": "mage/popup-window",
            "validation": "mage/validation/validation",
            "breadcrumbs": "Magento_Theme/js/view/breadcrumbs",
            "jquery/ui": "jquery/compat",
            "cookieStatus": "Magento_Theme/js/cookie-status",
            "checkoutBalance": "Magento_Customer/js/checkout-balance",
            "address": "Magento_Customer/js/address",
            "changeEmailPassword": "Magento_Customer/js/change-email-password",
            "passwordStrengthIndicator": "Magento_Customer/js/password-strength-indicator",
            "zxcvbn": "Magento_Customer/js/zxcvbn",
            "addressValidation": "Magento_Customer/js/addressValidation",
            "showPassword": "Magento_Customer/js/show-password",
            "Magento_Customer/address": "Magento_Customer/js/address",
            "Magento_Customer/change-email-password": "Magento_Customer/js/change-email-password",
            "globalSessionLoader": "Magento_Customer/js/customer-global-session-loader.js",
            "priceBox": "Magento_Catalog/js/price-box",
            "priceOptionDate": "Magento_Catalog/js/price-option-date",
            "priceOptionFile": "Magento_Catalog/js/price-option-file",
            "priceOptions": "Magento_Catalog/js/price-options",
            "priceUtils": "Magento_Catalog/js/price-utils",
            "compareList": "Magento_Catalog/js/list",
            "relatedProducts": "Magento_Catalog/js/related-products",
            "upsellProducts": "Magento_Catalog/js/upsell-products",
            "productListToolbarForm": "Magento_Catalog/js/product/list/toolbar",
            "catalogGallery": "Magento_Catalog/js/gallery",
            "catalogAddToCart": "Magento_Catalog/js/catalog-add-to-cart",
            "escaper": "Magento_Security/js/escaper",
            "quickSearch": "Smile_ElasticsuiteCore/js/form-mini",
            "Magento_Search/form-mini": "Magento_Search/js/form-mini",
            "catalogSearch": "Magento_CatalogSearch/form-mini",
            "addToCart": "Magento_Msrp/js/msrp",
            "bundleOption": "Magento_Bundle/bundle",
            "priceBundle": "Magento_Bundle/js/price-bundle",
            "slide": "Magento_Bundle/js/slide",
            "productSummary": "Magento_Bundle/js/product-summary",
            "creditCardType": "Magento_Payment/js/cc-type",
            "Magento_Payment/cc-type": "Magento_Payment/js/cc-type",
            "giftMessage": "Magento_Sales/js/gift-message",
            "ordersReturns": "Magento_Sales/js/orders-returns",
            "Magento_Sales/gift-message": "Magento_Sales/js/gift-message",
            "Magento_Sales/orders-returns": "Magento_Sales/js/orders-returns",
            "downloadable": "Magento_Downloadable/js/downloadable",
            "Magento_Downloadable/downloadable": "Magento_Downloadable/js/downloadable",
            "discountCode": "Magento_Checkout/js/discount-codes",
            "shoppingCart": "Magento_Checkout/js/shopping-cart",
            "regionUpdater": "Magento_Checkout/js/region-updater",
            "sidebar": "Magento_Checkout/js/sidebar",
            "checkoutLoader": "Magento_Checkout/js/checkout-loader",
            "checkoutData": "Magento_Checkout/js/checkout-data",
            "proceedToCheckout": "Magento_Checkout/js/proceed-to-checkout",
            "configurable": "Magento_ConfigurableProduct/js/configurable",
            "requireCookie": "Magento_Cookie/js/require-cookie",
            "cookieNotices": "Magento_Cookie/js/notices",
            "taxToggle": "Magento_Weee/js/tax-toggle",
            "Magento_Weee/tax-toggle": "Magento_Weee/js/tax-toggle",
            "giftOptions": "Magento_GiftMessage/js/gift-options",
            "Magento_GiftMessage/gift-options": "Magento_GiftMessage/js/gift-options",
            "uiElement": "Magento_Ui/js/lib/core/element/element",
            "uiCollection": "Magento_Ui/js/lib/core/collection",
            "uiComponent": "Magento_Ui/js/lib/core/collection",
            "uiClass": "Magento_Ui/js/lib/core/class",
            "uiEvents": "Magento_Ui/js/lib/core/events",
            "uiRegistry": "Magento_Ui/js/lib/registry/registry",
            "consoleLogger": "Magento_Ui/js/lib/logger/console-logger",
            "uiLayout": "Magento_Ui/js/core/renderer/layout",
            "buttonAdapter": "Magento_Ui/js/form/button-adapter",
            "chartJs": "chartjs/Chart.min",
            "chart.js": "chartjs/Chart.min",
            "tinymce": "tiny_mce_5/tinymce.min",
            "wysiwygAdapter": "mage/adminhtml/wysiwyg/tiny_mce/tinymce5Adapter",
            "pageCache": "Magento_PageCache/js/page-cache",
            "configurableVariationQty": "Magento_InventoryConfigurableProductFrontendUi/js/configurable-variation-qty",
            "multiShipping": "Magento_Multishipping/js/multi-shipping",
            "orderOverview": "Magento_Multishipping/js/overview",
            "payment": "Magento_Multishipping/js/payment",
            "billingLoader": "Magento_Checkout/js/checkout-loader",
            "cartUpdate": "Magento_Checkout/js/action/update-shopping-cart",
            "multiShippingBalance": "Magento_Multishipping/js/multi-shipping-balance",
            "recentlyViewedProducts": "Magento_Reports/js/recently-viewed",
            "subscriptionStatusResolver": "Magento_Newsletter/js/subscription-status-resolver",
            "newsletterSignUp": "Magento_Newsletter/js/newsletter-sign-up",
            "slick": "Magento_PageBuilder/js/resource/slick/slick",
            "jarallax": "Magento_PageBuilder/js/resource/jarallax/jarallax",
            "jarallaxVideo": "Magento_PageBuilder/js/resource/jarallax/jarallax-video",
            "Magento_PageBuilder/js/resource/vimeo/player": "vimeo/player",
            "Magento_PageBuilder/js/resource/vimeo/vimeo-wrapper": "vimeo/vimeo-wrapper",
            "jarallax-wrapper": "Magento_PageBuilder/js/resource/jarallax/jarallax-wrapper",
            "captcha": "Magento_Captcha/js/captcha",
            "Magento_Captcha/captcha": "Magento_Captcha/js/captcha",
            "transparent": "Magento_Payment/js/transparent",
            "Magento_Payment/transparent": "Magento_Payment/js/transparent",
            "orderReview": "Magento_Paypal/js/order-review",
            "Magento_Paypal/order-review": "Magento_Paypal/js/order-review",
            "paypalCheckout": "Magento_Paypal/js/paypal-checkout",
            "loadPlayer": "Magento_ProductVideo/js/load-player",
            "fotoramaVideoEvents": "Magento_ProductVideo/js/fotorama-add-video-events",
            "mageTranslationDictionary": "Magento_Translation/js/mage-translation-dictionary",
            "editTrigger": "mage/edit-trigger",
            "addClass": "Magento_Translation/js/add-class",
            "Magento_Translation/add-class": "Magento_Translation/js/add-class",
            "wishlist": "Magento_Wishlist/js/wishlist",
            "addToWishlist": "Magento_Wishlist/js/add-to-wishlist",
            "wishlistSearch": "Magento_Wishlist/js/search",
            "braintree": "https://js.braintreegateway.com/web/3.88.1/js/client.min.js",
            "braintreeCheckoutPayPalAdapter": "PayPal_Braintree/js/view/payment/adapter",
            "rangeSlider": "Smile_ElasticsuiteCatalog/js/range-slider-widget"
        }
    },
    onBuildWrite(moduleName, path, contents) {
        let uglifyJS = require.nodeRequire('uglify-js');
        let uglifyES = require.nodeRequire('uglify-es');
        let result = uglifyJS.minify(contents);

        if (result.error) {
            result = uglifyES.minify(contents);

            if (result.error) {
                throw new Error(result.error);
            }
        }

        return result.code;

    }
})
