<?php

namespace TheITNerd\UX\Rewrite\Magento\Catalog\Block\Product\ProductList;

use Magento\Catalog\Block\Product\Context;
use Magento\Catalog\Model\Product\Visibility as ProductVisibility;
use Magento\Checkout\Model\ResourceModel\Cart as CartResourceModel;
use Magento\Checkout\Model\Session as CheckoutSession;
use Magento\Framework\Module\Manager;
use TheITNerd\UX\Helper\Product;

class Related extends \Magento\Catalog\Block\Product\ProductList\Related
{
    public function __construct(
        Context                    $context,
        CartResourceModel          $checkoutCart,
        ProductVisibility          $catalogProductVisibility,
        CheckoutSession            $checkoutSession,
        Manager                    $moduleManager,
        protected readonly Product $productHelper,
        array                      $data = []
    )
    {
        parent::__construct($context, $checkoutCart, $catalogProductVisibility, $checkoutSession, $moduleManager, $data);
    }

    /**
     * {@inheritDoc}
     */
    public function setTemplate($template)
    {
        if($this->productHelper->isBuyTogetherEnabled()) {
            $template = 'TheITNerd_UX::Magento/Catalog/product/list/related.phtml';
        }

        return parent::setTemplate($template); // TODO: Change the autogenerated stub
    }
}
