<script type="text/x-magento-init">
{
    "#telephone": {
        "TheITNerd_Core/js/inputMask": {
            "mask": "(00) 0000-00000"
        }
    },
    "#zip": {
        "TheITNerd_Core/js/inputMask": {
            "mask": "00000-000"
        }
    },
    "#vat_id": {
        "TheITNerd_Brasil/js/cpfCnpjField": {
            "mask": "00000-000"
        }
    },
    "#taxvat": {
        "TheITNerd_Brasil/js/cpfCnpjField": {}
    }
}
</script>
